import { mkdir, cp, writeFile } from 'node:fs/promises';
import { restaurant as r, prices, reviews } from '../src/config.mjs';
import { Container, Section, SectionHeading, Button, TextLink, ImageFrame, VerticalLabel, Navigation, Footer, MenuHighlight, PriceRow, ReviewCard, arrow } from '../src/components.mjs';
import { Wave, Blossom, SakuraTree, SakuraBranch, KoiBackdrop, OrnamentDivider, patterns } from '../src/artwork.mjs';
import { DragonSky } from '../src/mural.mjs';

const hero = `<section class="hero" id="start" aria-labelledby="hero-title">${ImageFrame('shared-table','Gemeinsam Sushi und asiatische Spezialitäten am gedeckten Tisch bei OTTOYAMI genießen',{className:'hero-image',eager:true,sizes:'100vw',width:1920,height:1280})}<div class="hero-shade"></div><div class="petals" aria-hidden="true">${Array.from({length:7},(_,i)=>`<span style="--petal:${i}"></span>`).join('')}</div>${Container(`<div class="hero-content"><h1 id="hero-title">Asiatisches All You Can Eat<br><em>mitten im sechsten Bezirk</em></h1><p class="hero-description">Sushi, Maki und Gegrilltes bestellst du am Tisch per iPad, und die Küche bereitet jede Runde frisch für dich zu. Unter der Woche zahlst du mittags 17,90 €, abends und am Wochenende 26,90 €.</p><div class="button-group">${Button('Tisch reservieren')}${Button('Preise und Zeiten ansehen','#all-you-can-eat',true,false)}</div></div><div class="hero-aside">${VerticalLabel('いただきます')}<span>Guten Appetit.</span></div>`)}<div class="hero-bottom"><span>OTTO-BAUER-GASSE 20 · 1060 WIEN</span><span>TÄGLICH 11:00–22:30 UHR</span></div></section>`;

const intro = Section('ueber-uns',Container(`<div class="intro-top"><span class="eyebrow">01 / WILLKOMMEN BEI OTTOYAMI</span><span class="seal" lang="ja" aria-hidden="true">美<br>味</span></div><div class="intro-grid">${SectionHeading('ueber-uns','','Wenn sich niemand auf ein Gericht einigen kann,<br><em>muss das bei uns auch keiner</em>')}<div class="intro-copy reveal"><p class="body-large">Jede Person am Tisch bestellt, worauf sie gerade Lust hat, ob das eine Runde Lachs-Maki ist oder ein paar Spieße vom Grill.</p><p>Weil alles im Preis enthalten ist, kannst du Neues probieren, ohne vorher auszurechnen, was es kostet.</p>${TextLink('Unsere Küche kennenlernen','#speisekarte')}</div></div>${OrnamentDivider()}`),'intro');

const wave = Section('vielfalt',`${Wave()}${Container(`<div class="wave-copy">${SectionHeading('vielfalt','VON DER ERSTEN BIS ZUR LETZTEN RUNDE','Probier ruhig etwas,<br><em>das du sonst nie bestellen würdest</em>')}<p>Schmeckt es dir, bestellst du es in der nächsten Runde einfach wieder, und wenn nicht, wählst du beim nächsten Mal etwas anderes.</p>${TextLink('Zur aktuellen Speisekarte','https://www.ottoyami.at/menu')}</div>`)}`,'wave-section');

const menu = Section('speisekarte',Container(`<div class="section-topline"><p class="eyebrow">02 / VIELE KLEINE GLÜCKSMOMENTE</p>${TextLink('Die ganze Speisekarte','https://www.ottoyami.at/menu')}</div><h2 class="sr-only" id="speisekarte-title">Unsere Küche</h2><div class="menu-grid">${[
 {image:'grilled-skewers',alt:'Glasierte gegrillte Spieße auf einem Teller mit Zitrone',japanese:'焼き物',title:'Vom Grill',description:'Frisch gegrillt, fein gewürzt. Für alle, die es herzhaft lieben.'},
 {image:'sushi-platter',alt:'Eine lange Platte mit frisch zubereiteten Sushi-Rollen bei OTTOYAMI',japanese:'寿司',title:'Sushi & Maki',description:'Mit Sorgfalt gerollt. Kleine Kunstwerke, große Lieblingsstücke.'},
 {image:'salmon-roll',alt:'Aburi Salmon Rolls mit Lachs und Avocado aus der offiziellen OTTOYAMI-Galerie',japanese:'海の幸',title:'Fein aus dem Meer',description:'Zarter Lachs, feine Aromen. Entdecke unsere asiatische Vielfalt.'},
].map((item,index)=>MenuHighlight({...item,index})).join('')}</div>`),'food-section');

const pricing = Section('all-you-can-eat',KoiBackdrop()+Container(`<div class="pricing-header">${SectionHeading('all-you-can-eat','03 / ALL YOU CAN EAT','Ein Preis pro Person,<br><em>egal wie viele Runden du bestellst</em>')}<p>Wer von Montag bis Freitag bis 17 Uhr kommt, isst für 17,90 €. Ab 17 Uhr sowie an Wochenenden und Feiertagen kostet All You Can Eat 26,90 €.</p></div><div class="price-list reveal">${prices.map(PriceRow).join('')}</div><div class="pricing-bottom"><p>Die Preise gelten pro Person.<br><span>Was gerade auf der Karte steht, zeigt dir die aktuelle Speisekarte.</span></p>${Button('Tisch reservieren')}</div>`),'pricing-section');

const steps = Section('so-gehts',Container(`<div class="steps-intro">${SectionHeading('so-gehts','GANZ ENTSPANNT GENIESSEN','Du bestellst direkt am Tisch,<br><em>so oft du möchtest</em>')}<div class="sakura-branch">${SakuraBranch()}<div class="sakura-petals" aria-hidden="true"></div></div></div><div class="steps-list">${[
 ['Reservieren und Platz nehmen','Mit einer Reservierung ist dein Tisch frei, wenn du ankommst.'],
 ['Am iPad auswählen','Du tippst an, was du probieren möchtest, und schickst die Bestellung direkt in die Küche.'],
 ['Nachbestellen','Die Gerichte kommen frisch zubereitet an den Tisch, und sobald der Teller leer ist, bestellst du die nächste Runde.'],
].map(([title,body],index)=>`<div class="step reveal"><span>0${index+1}</span><div><h3>${title}</h3><p>${body}</p></div></div>`).join('')}</div>`,'steps-grid'),'steps-section');

const reviewSection =Section('gaestestimmen',Container(`<div class="reviews-heading">${SectionHeading('gaestestimmen','04 / GUTE ZEITEN. GUTE WORTE.','Was Gäste nach ihrem Besuch<br><em>geschrieben haben</em>')}<div class="google-summary"><span class="google-word">Google</span><div class="blossom-rating" aria-hidden="true">${Blossom().repeat(5)}</div><p>Ausgewählte 5-Sterne-Stimmen.</p>${TextLink('Alle Bewertungen ansehen',r.maps)}</div></div><div class="reviews-track">${reviews.map(ReviewCard).join('')}</div><p class="review-source">Ausgewählte Google-Rezensionen · Auszüge im Original · dokumentiert bei <a href="https://wanderlog.com/place/details/3980386">Wanderlog</a>. Keine Live-Bewertung.</p>`),'reviews-section');

const galleryImages = [
 ['courtyard','Lichtdurchfluteter Innenhof von OTTOYAMI mit rosa Kirschblütendekoration','Ein kleiner Urlaub. Mitten in Wien.'],
 ['sushi-platter','Frische Sushi-Rollen, auf einer langen Platte angerichtet','Für die nächste Lieblingsrunde.'],
 ['dining-room','Der OTTOYAMI-Gastraum mit Holzmöbeln, gewölbter Decke und japanischem Wandbild','Zusammen schmeckt es am besten.'],
 ['restaurant','Liebevoll gedeckte Tische im OTTOYAMI-Restaurant','Noch ein bisschen bleiben.'],
];
// TEMPORARY: dragon line drawing behind the gallery, see src/mural.mjs.
const gallery = Section('galerie',DragonSky()+Container(`<div class="gallery-heading">${SectionHeading('galerie','05 / EIN PLATZ ZUM BLEIBEN','So sieht es aus,<br><em>wenn du bei uns Platz nimmst</em>')}<p>Ob im Innenhof unter dem Glasdach oder im Gastraum mit dem großen Wandbild, Platz gibt es für die schnelle Mittagspause genauso wie für einen langen Abend.</p></div><div class="gallery-grid">${galleryImages.map(([name,alt,caption],index)=>`<figure class="gallery-item gallery-item--${index+1} reveal"><button class="gallery-open" data-image="assets/ottoyami-${name}-1440.webp" data-alt="${alt}" aria-label="Bild vergrößern: ${alt}">${ImageFrame(name,alt,{width:1200,height:800,sizes:index===0?'(max-width: 767px) 100vw, 65vw':'(max-width: 767px) 100vw, 40vw'})}<span class="image-expand" aria-hidden="true">↗\uFE0E</span></button><figcaption><span>0${index+1}</span>${caption}</figcaption></figure>`).join('')}</div><div class="gallery-bottom">${TextLink('Mehr entdecken','https://www.ottoyami.at/gallery')}<span class="eyebrow">FOOD. FRIENDS. OTTOYAMI.</span></div>`),'gallery-section');

const contact = Section('kontakt',Container(`<div class="contact-main">${SectionHeading('kontakt','06 / WIR FREUEN UNS AUF DICH','Otto-Bauer-Gasse 20,<br><em>täglich von 11 bis 22:30 Uhr</em>')}<p class="contact-lead">Bestellungen nimmt die Küche bis 22 Uhr an. Reserviere online, oder ruf unter ${r.phone} an, wenn du mit einer größeren Gruppe kommst.</p><div class="button-group">${Button('Tisch reservieren')}${Button('Route öffnen',r.maps,true)}</div></div><div class="contact-details"><div><p class="eyebrow">HIER FINDEST DU UNS</p><address>OTTOYAMI<br>${r.street}<br>${r.postcode} ${r.city}, Österreich</address></div><div><p class="eyebrow">JEDEN TAG FÜR DICH DA</p><dl><div><dt>Restaurant</dt><dd>${r.hours} Uhr</dd></div><div><dt>Küche</dt><dd>${r.kitchenHours} Uhr</dd></div></dl></div><div><p class="eyebrow">SAG HALLO</p><a href="${r.phoneHref}">${r.phone}</a><br><a href="mailto:${r.email}">${r.email}</a></div></div>`,'contact-grid')+`<div class="tree-petals" aria-hidden="true">${'<span></span>'.repeat(7)}</div>${SakuraTree()}`,'contact-section');

const structuredData={
 '@context':'https://schema.org','@type':'Restaurant','@id':r.website+'/#restaurant',name:r.name,url:r.website,
 image:r.website+'/assets/ottoyami-shared-table-1920.webp',telephone:r.phone,email:r.email,
 address:{'@type':'PostalAddress',streetAddress:r.street,postalCode:r.postcode,addressLocality:r.city,addressCountry:'AT'},
 servesCuisine:['Asian','Sushi','Japanese'],priceRange:'€€',acceptsReservations:true,
 openingHoursSpecification:[{'@type':'OpeningHoursSpecification',dayOfWeek:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],opens:'11:00',closes:'22:30'}],
 sameAs:[r.instagram,r.facebook],hasMenu:r.website+'/menu',
};
const html=`<!doctype html><html lang="de" data-theme="dark"><head><meta charset="UTF-8"><script>try{var t=localStorage.getItem('ottoyami-theme');if(t==='light'||t==='dark')document.documentElement.dataset.theme=t}catch(e){}</script><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#15120F"><title>OTTOYAMI Wien | Asian All You Can Eat</title><meta name="description" content="Asiatisches All You Can Eat in 1060 Wien: Sushi, Maki und Gegrilltes per iPad bestellen, unter der Woche mittags für 17,90 €. Reserviere deinen Tisch in der Otto-Bauer-Gasse 20."><link rel="canonical" href="https://www.ottoyami.at/"><meta property="og:type" content="website"><meta property="og:locale" content="de_AT"><meta property="og:title" content="OTTOYAMI Wien | Asian All You Can Eat"><meta property="og:description" content="Einmal Asien. Immer wieder OTTOYAMI. Sushi, asiatische Lieblingsgerichte und eine gute Zeit im Herzen von Wien."><meta property="og:url" content="https://www.ottoyami.at/"><meta property="og:image" content="https://www.ottoyami.at/assets/ottoyami-shared-table-1920.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="preload" href="assets/editorial-regular.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="styles.css"><script type="application/ld+json">${JSON.stringify(structuredData)}</script><script src="app.js" defer></script><noscript><style>@media(max-width:1100px){.site-header{position:relative;background:var(--color-background);color:var(--color-ink)}.nav-shell{height:auto;flex-wrap:wrap;padding-block:24px}.nav-actions{display:none}#main-navigation{display:flex;flex-wrap:wrap;gap:8px 24px}#main-navigation>a{font-size:14px}.hero-aside{display:none}}</style></noscript></head><body>${Navigation()}<main id="main">${hero}${intro}${wave}${menu}${pricing}${steps}${reviewSection}${gallery}${contact}</main>${Footer()}<dialog class="lightbox" aria-label="Bildergalerie"><button class="lightbox-close" aria-label="Galerie schließen">×</button><figure><img width="1440" height="960" alt=""><figcaption></figcaption></figure><div class="lightbox-controls"><button class="lightbox-prev" aria-label="Vorheriges Bild">←</button><span aria-live="polite" class="lightbox-count"></span><button class="lightbox-next" aria-label="Nächstes Bild">→</button></div></dialog></body></html>`;
await mkdir('dist',{recursive:true});
await cp('public','dist',{recursive:true});
await writeFile('dist/index.html',html);
// TEMPORARY: app.js loads the dragon geometry to re-shape it on scroll.
await cp('src/mural.mjs','dist/dragon.js');
for (const [name,svg] of Object.entries(patterns)) await writeFile(`dist/assets/${name}`,svg);
await writeFile('dist/favicon.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="4" fill="#0B0B0B"/><rect x="5" y="5" width="54" height="54" fill="none" stroke="#fff" stroke-width="3"/><g fill="#fff" font-family="Consolas,Menlo,monospace" font-size="19"><text x="11" y="29" textLength="42" lengthAdjust="spacingAndGlyphs">OTTO</text><text x="11" y="50" textLength="42" lengthAdjust="spacingAndGlyphs">YAMI</text></g></svg>`);
await writeFile('dist/robots.txt','User-agent: *\nAllow: /\nSitemap: https://www.ottoyami.at/sitemap.xml\n');
await writeFile('dist/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://www.ottoyami.at/</loc></url></urlset>');
console.log('Built OTTOYAMI → dist/ (static HTML, local fonts and optimized WebP images)');
